
package uas;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class login extends javax.swing.JFrame {

    public void empty_data(){       //MEMBUAT METHOD EMPTY DATA
        txtUser.setText("");        //MENGKOSONGKAN TEXTFIELD USERNAME
        txtPass.setText("");        //MENGKOSONGKAN TEXTFIELD PASSWORD
    }
            
    public login() {
        initComponents();                   //MEMANGGIL METHOD INITCOMPONENTS
        this.setLocationRelativeTo(null);   //OUTPUT AKAN AUTOMATIS BERADA DI TENGAH
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        btLogin = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        BG = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 113, 173));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btLogin.setBackground(new java.awt.Color(82, 62, 62));
        btLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btLogin.setText("LOGIN");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 320, -1));

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 170, 40));
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 170, 40));

        btRegister.setText("Tidak memiliki akun? ");
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 160, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 140, 40));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 120, 40));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FORM LOGIN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/images.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 300, 170));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/bandara.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 380, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 380, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
//        BUTTON REGISTER ACTION
        Register reg = new Register();      //MENDEKLARASIKAN KELAS REGISTER UNTUK DIPANGGIL      
        reg.setVisible(true);               //MENAMPILKAN TAMPILAN REGISTER MENU
        dispose();                          //MENUTUP TAMPILAN REGISTER
    }//GEN-LAST:event_btRegisterActionPerformed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        //BUTTON LOGIN ACTION
        try {
            if (txtUser.getText().equals("")                                        //PERCABANGAN JIKA TEXTFIELD USERNAME KOSONG
            || String.valueOf(txtPass.getPassword()).equals("")) {                  //ATAU JIKA TEXTFIELD PASSWORD KOSONG
                JOptionPane.showMessageDialog                                       //MAKA AKAN MENAMPILKAN JOPTION ERROR MESSAGE
                    (this, "Form Login Tidak Boleh Kosong", "alert..!",             //YANG BERISI FORM LOGIN TIDAK BOLEH KOSONG
                    JOptionPane.ERROR_MESSAGE);
            }
            else{                                                                   
                String sql = "SELECT * FROM data_user WHERE "                       //MENGAMBIL DATA DARI DATABASE DIMANA               
                        + "Username = '"+txtUser.getText()+"' "                     //JIKA TEXTFIELD USERNAME = DATABASE USERNAME
                        + "AND Password = "                                         //LOGIKA DAN
                        + "'"+String.valueOf(txtPass.getPassword())+"' ";           //JIKA TEXTFIELD PASSWORD = DATABASE PASSWORD
                java.sql.Connection conn =  (Connection)Database.configDB();        //MENGKONEKSIKAN KE DATABASE
                java.sql.Statement stm = conn.createStatement();                    //MEMBUAT STATEMENT
                java.sql.ResultSet rs = stm.executeQuery(sql);                      //MENGEKSEKUSI DATABASE KE DALAM RS
                if (rs.next()) {                                                    //JIKA USERNAME DAN PASSWORD SAMA DENGAN DI DATABASE MAKA
                    JOptionPane.showMessageDialog
                    (null, "Login Berhasil", 
                           "succes", JOptionPane.INFORMATION_MESSAGE);  //YANG BERISI LOGIN BERHASIL
                    Pemesanan pesan = new Pemesanan();                              //MENDEKLARASIKAN KELAS PESAN UNTUK DIPANGGIL
                    pesan.setVisible(true);                                         //MENAMPILKAN TAMPILAN PESAN MENU
                    dispose();                                                      //TAMPILAN LOGIN TERTUTUP
                }else {                                                             //JIKA USERNAME DAN PASSWORD TIDAK SAMA DENGAN DI DATABASE MAKA
                    JOptionPane.showMessageDialog                                   //MENAMPILKAN JOPTIONPANE
                        (this,                                                      
                        "Username atau Password salah",                             //TAMPILAN JOPTIONPANE "USERNAME ATAU PASSWORD SALAH"
                        "Login Error", JOptionPane.ERROR_MESSAGE);                  //JUDUL JOPTION "LOGIN ERROR"
                    empty_data();                                                   //MENGKOSONGKAN TEXTFIELD USERNAME DAN PASSWORD
                   
                }
            }
            
        } catch (SQLException e) {                                                  //JIKA TERJADI ERROR DALAM TRY
            JOptionPane.showMessageDialog(this, "Gagal Login");
            System.out.println(""+e.getMessage());
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private java.awt.Panel panel1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
