package uas;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;


public class Register extends javax.swing.JFrame {

public void empty_data(){       //Method untuk mereset textfield
    txtNama.setText("");        //txtNama kosong
    txtUser.setText("");        //txtUsername kosong
    txtPass.setText("");        //txtPassword kosong
    Password.setText("");       //txtUlangPassword kosong
    
}
    public Register() {
        initComponents();       //untuk menampilkan jform
        this.setLocationRelativeTo(null);   //output auto berada di tengah
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLnama = new javax.swing.JLabel();
        JLusername = new javax.swing.JLabel();
        JLpassword = new javax.swing.JLabel();
        JLulang = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        btBatal = new javax.swing.JButton();
        btDaftar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        JLregister = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        Password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 175));

        JLnama.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JLnama.setText("NAMA");

        JLusername.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JLusername.setText("USERNAME");

        JLpassword.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JLpassword.setText("PASSWORD");

        JLulang.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        JLulang.setText("ULANG PASSWORD");

        txtNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btBatal.setBackground(new java.awt.Color(0, 93, 161));
        btBatal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btBatal.setText("BATAL");
        btBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalActionPerformed(evt);
            }
        });

        btDaftar.setBackground(new java.awt.Color(0, 93, 161));
        btDaftar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btDaftar.setText("DAFTAR");
        btDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDaftarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 93, 161));

        JLregister.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JLregister.setForeground(new java.awt.Color(0, 187, 216));
        JLregister.setText("REGISTER FORM");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(JLregister, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLregister, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setText("Login now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("sudah memiliki akun?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(JLnama, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JLpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JLusername, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(JLulang)))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                .addComponent(txtUser)
                                .addComponent(txtPass)
                                .addComponent(Password))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(245, 245, 245))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(209, 209, 209))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLnama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLusername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLulang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDaftarActionPerformed
        //Button Daftar Action
        boolean same = Arrays.equals(txtPass.getPassword(), Password.getPassword());           //MENDEKLARASIKAN BOOLEAN UNTUK KONDISI PASSWORD DAN ULANG PASSWORD SAMA
        boolean notsame = !same;                                                               //MENDEKLARASIKAN BOOLEAN UNTUK KONDISI PASSWORD DAN ULANG PASSWORD TIDAK SAMA
        try {                               
           if (txtUser.getText().equals("")                                                    //PERCABANGAN JIKA TEXTFIELD USER KOSONG
               || txtNama.getText().equals("")                                                 //PERCABANGAN JIKA TEXTFIELD NAMA KOSONG
               || String.valueOf(txtPass.getPassword()).equals("")                             //PERCABANGAN JIKA TEXTFIELD PASSWORD KOSONG
               || String.valueOf(Password.getPassword()).equals("") )                          //PERCABANGAN JIKA TEXTFIELD ULANG PASSWORD KOSONG
            {
                JOptionPane.showMessageDialog
                    (this, "Data tidak boleh kosong", "error", JOptionPane.ERROR_MESSAGE);     //AKAN KELUAR TAMPILAN JOPTION ERROR
                empty_data();                                                                  //MENGKOSONGKAN SEMUA TEXTFIELD
            } 
           else if (same) {     //PERCABANGAN JIKA PASSWORD DAN ULANG PASSWORD SAMA
                String sql = "INSERT INTO data_user VALUES "                                    //MEMASUKKAN NILAI KE DALAM DATABASE
                        + "('"+txtNama.getText()+"' , "                                         //KOLOM 1 PADA DATABASE DIAMBIL DARI TEXTFIELD NAMA
                        + "'"+txtUser.getText()+"' , "                                          //KOLOM 2 PADA DATABASE DIAMBIL DARI TEXTFIELD USERNAME
                        + "'"+String.valueOf(txtPass.getPassword())+"' )";                      //KOLOM 3 PADA DATABASE DIAMBIL DARI TEXTFIELD PASSWORD
                java.sql.Connection conn =(Connection)Database.configDB()  ;                    //MENGKONEKSIKAN KEDATABASE DARI KELAS DATABASE METHOD CONFIGDB
                PreparedStatement pstm = conn.prepareStatement(sql);                            //MEMBUAT STATEMENT MYSQL
                pstm.execute();                                                                 //MENGEKSEKUSI STATEMENT
                JOptionPane.showMessageDialog(null,"Registrasi Berhasil");                      //MENAMPILKAN JOPTION "REGISTRASI BERHASIL"
                empty_data();                                                                   //MENGKOSONGKAN SEMUA TEXTFIELD
            } 
            else if(notsame){                                                                   //JIKA PASSWORD DAN ULANG PASSWORD TIDAK SAMA
                JOptionPane.showMessageDialog                                                   //MENAMPILKAN JOPTIONMESSAGE
                    (this, "Password doesn't match", "error", JOptionPane.ERROR_MESSAGE);       //BERISI PASSWORD DOESN'T MATCH
                Password.setText("");                                                           //TEXTFIELD ULANG PASSWORD AKAN DI KOSONGI
            }
            
          
                       
       }catch(HeadlessException | SQLException e){                                              //JIKA TERJADI ERROR DALAM PENGKONEKSIAN DATABASE
          JOptionPane.showMessageDialog(this, e.getMessage());                                  //MENAMPILKAN ERRORNYA DIMANA
               } 
    }//GEN-LAST:event_btDaftarActionPerformed

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed
       //BUTTON BATAL ACTION
        int answer=JOptionPane.showConfirmDialog                                                 //MENYIMPAN HASIL OK_OPTION PADA INT ANSWER
            (null,"Apakah Anda Ingin Membatalkan Registrasi?","Batal",JOptionPane.OK_OPTION);    //MENAMPILKAN JOPTION BATAL
       if (answer==JOptionPane.OK_OPTION){                                                       //JIKA PENGGUNA MENGKLIK OK MAKA
           dispose();                                                                            //FORM REGISTRASI AKAN TERTUTUP
       }
    }//GEN-LAST:event_btBatalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //BUTTON LOGIN ACTION
        login aa = new login();                                                                  //MENDEKLARASIKAN KELAS LOGIN UNTUK DIPANGGIL 
        aa.setVisible(true);                                                                     //MENAMPILKAN TAMPILAN LOGIN MENNU
        dispose();                                                                               //TAMPILAN REGISTER TERTUTUP   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {                                                     //METHOD MAIN
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);                                                //MENAMPILKAN KELAS REGISTER JIKA DI RUN
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLnama;
    private javax.swing.JLabel JLpassword;
    private javax.swing.JLabel JLregister;
    private javax.swing.JLabel JLulang;
    private javax.swing.JLabel JLusername;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btDaftar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
